import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {spawnSync} from 'node:child_process';import {readFileSync} from 'node:fs';import {handleApi,handleMedia,signSession,verifySession,verifyStripeSignature,validateCart,sniffType} from '../server/app.js';
const origin='https://juplifestudio.com',secret='a-long-session-secret-with-32-characters';const request=(path,body,headers={})=>new Request(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const api=(request,env={})=>handleApi({request,env});
const signature=(raw,now=Date.now())=>{const t=Math.floor(now/1000);return `t=${t},v1=${createHmac('sha256','whsec_test').update(t+'.'+raw).digest('hex')}`};
test('sessions expire, reject tampering, wrong secret and oversized tokens',async()=>{const t=Date.now(),token=await signSession(secret,t);assert.equal(await verifySession(token,secret,t),true);assert.equal(await verifySession(token,secret,t+28800000),false);assert.equal(await verifySession(token+'x',secret,t),false);assert.equal(await verifySession(token,'another-long-secret-with-32-characters',t),false);assert.equal(await verifySession('a'.repeat(1025),secret,t),false)});
test('Stripe signatures accept genuine raw bodies and reject mutation and replay',async()=>{const raw='{"id":"evt_example"}',t=Date.now();assert.equal(await verifyStripeSignature(raw,signature(raw,t),'whsec_test',t),true);assert.equal(await verifyStripeSignature(raw+' ',signature(raw,t),'whsec_test',t),false);assert.equal(await verifyStripeSignature(raw,signature(raw,t),'whsec_test',t+301000),false)});
test('cart rejects unknown, duplicate and invalid quantities; strips client prices',()=>{assert.deepEqual(validateCart([{id:'coaster-set',quantity:2,price:1}]),[{id:'coaster-set',quantity:2}]);for(const items of [[],[{id:'fake',quantity:1}],[{id:'coaster-set',quantity:0}],[{id:'coaster-set',quantity:11}],[{id:'coaster-set',quantity:1.5}],[{id:'coaster-set',quantity:1},{id:'coaster-set',quantity:2}]])assert.throws(()=>validateCart(items))});
test('checkout fails closed and rejects foreign origin before touching Stripe',async()=>{assert.equal((await api(request('/api/checkout',{items:[]}))).status,503);assert.equal((await api(request('/api/checkout',{}, {Origin:'https://evil.example'}))).status,403)});
test('catalog does not expose secrets or enable buying without configuration',async()=>{const r=await api(new Request(origin+'/api/catalog'),{STRIPE_SECRET_KEY:'super-secret'});const b=await r.json();assert.equal(b.checkoutReady,false);assert.equal(b.products.length,7);assert.ok(b.products.every(p=>!p.available&&(['hibiscus','proof-of-coin','jup-signature','sweet-coast-jar'].includes(p.id)?p.amount>0&&p.currency==='USD':p.amount===null)&&!p.priceEnv));assert.ok(!JSON.stringify(b).includes('super-secret'))});
test('unauthenticated admin cannot upload, read orders or change media',async()=>{for(const path of ['/api/admin/media','/api/admin/orders','/api/admin/status'])assert.equal((await api(new Request(origin+path),{DB:{}})).status,401);assert.equal((await api(request('/api/admin/media',{}),{DB:{}})).status,401)});
test('bad login and oversized login JSON are rejected',async()=>{const DB={prepare:()=>({bind(){return this},run:async()=>({}),first:async()=>({count:1})})},env={DB,ADMIN_PASSWORD:'strong-password-example',SESSION_SECRET:secret};assert.equal((await api(request('/api/admin/login',{password:'wrong'}),env)).status,401);assert.equal((await api(request('/api/admin/login',{password:'x'.repeat(17000)}),env)).status,413)});
test('login cookie is HttpOnly Secure SameSite=Strict',async()=>{const DB={prepare:()=>({bind(){return this},run:async()=>({}),first:async()=>({count:1})})};const r=await api(request('/api/admin/login',{password:'strong-password-example'}),{DB,ADMIN_PASSWORD:'strong-password-example',SESSION_SECRET:secret});assert.equal(r.status,200);assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Strict/)});
test('file signature validation rejects active SVG and spoofed images',()=>{assert.equal(sniffType(Uint8Array.from([137,80,78,71,13,10,26,10]),'image/png'),true);assert.equal(sniffType(new TextEncoder().encode('<svg></svg>'),'image/png'),false);assert.equal(sniffType(new TextEncoder().encode('<svg></svg>'),'image/svg+xml'),false)});
test('draft media is private; public video supports byte ranges and HEAD',async()=>{const id='12345678-1234-1234-1234-123456789abc';let published=0;const env={DB:{prepare:()=>({bind(){return this},first:async()=>({published,object_key:'file.mp4',content_type:'video/mp4'})})},MEDIA:{head:async()=>({size:100,httpEtag:'"etag"'}),get:async(key,options)=>({body:new Uint8Array(options?.range?.length||100)})}};const url=origin+'/media/'+id;assert.equal((await handleMedia({request:new Request(url),env})).status,404);published=1;let r=await handleMedia({request:new Request(url,{headers:{Range:'bytes=20-29'}}),env});assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),'bytes 20-29/100');assert.equal((await r.arrayBuffer()).byteLength,10);r=await handleMedia({request:new Request(url,{method:'HEAD'}),env});assert.equal(r.headers.get('Content-Length'),'100');assert.equal((await r.arrayBuffer()).byteLength,0);assert.equal((await handleMedia({request:new Request(url,{headers:{Range:'bytes=101-200'}}),env})).status,416)});
test('checkout uses configured Stripe prices and creates pending order only',async()=>{const originalFetch=globalThis.fetch,seen=[];const DB={prepare:sql=>({bind(...args){this.args=args;return this},run:async function(){seen.push({sql,args:this.args});return{}},first:async()=>({count:1})})};const env={DB,SESSION_SECRET:secret,SITE_URL:origin,STORE_READY:'true',POLICIES_APPROVED:'true',STRIPE_SECRET_KEY:'sk_test',STRIPE_WEBHOOK_SECRET:'whsec_test',STRIPE_SHIPPING_RATE:'shr_test',STRIPE_PRICE_COASTERS:'price_server'};try{globalThis.fetch=async(url,options)=>{if(url.includes('/prices/'))return Response.json({active:true,type:'one_time',unit_amount:4200,currency:'usd'});const form=new URLSearchParams(options.body);assert.equal(form.get('line_items[0][price]'),'price_server');assert.equal(form.get('line_items[0][quantity]'),'2');assert.equal(form.get('mode'),'payment');assert.equal(form.get('consent_collection[terms_of_service]'),null);assert.match(form.get('custom_text[submit][message]'),/shipping-returns/);assert.match(form.get('custom_text[submit][message]'),/privacy/);assert.equal(form.get('shipping_options[0][shipping_rate]'),'shr_test');assert.equal(form.get('shipping_address_collection[allowed_countries][0]'),'US');assert.equal(form.get('payment_method_types[0]'),null);assert.equal(options.headers['Stripe-Version'],'2026-08-26.dahlia');assert.ok(options.headers['Idempotency-Key']);return Response.json({id:'cs_test_example',url:'https://checkout.stripe.com/c/pay/test'})};const r=await api(request('/api/checkout',{requestId:'12345678-1234-1234-1234-123456789abc',items:[{id:'coaster-set',quantity:2,amount:1}]}),env);assert.equal(r.status,200);assert.equal(seen.at(-1).args.at(-1),'pending')}finally{globalThis.fetch=originalFetch}});
test('real SQLite webhook batch deduplicates and preserves paid/fulfilled states',async()=>{const statements=[];const DB={prepare:sql=>({bind(...args){return{sql,args}}}),batch:async list=>{statements.push(list);return[]}};async function event(id,type,status){const raw=JSON.stringify({id,type,data:{object:{id:'cs_test_order',payment_status:status,amount_total:4200,currency:'usd',metadata:{studio:'jup-life',cart:'[{"id":"coaster-set","quantity":1}]'}}}});const r=await api(new Request(origin+'/api/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':signature(raw)},body:raw}),{DB,STRIPE_WEBHOOK_SECRET:'whsec_test'});assert.equal(r.status,200)}await event('evt_paid','checkout.session.completed','paid');await event('evt_paid','checkout.session.completed','paid');await event('evt_late','checkout.session.expired','unpaid');const program=`import sqlite3,json,sys\ndb=sqlite3.connect(':memory:')\na=json.load(sys.stdin)\ndb.executescript(a['schema'])\nfor batch in a['statements']:\n with db:\n  for s in batch: db.execute(s['sql'],s['args'])\nassert db.execute('select count(*) from orders').fetchone()[0]==1\nassert db.execute('select count(*) from stripe_events').fetchone()[0]==2\nassert db.execute('select status from orders').fetchone()[0]=='paid'\ndb.execute("update orders set status='fulfilled'")\ns=a['statements'][-1][0]\nargs=s['args'];args[-1]='evt_later'\ndb.execute(s['sql'],args)\nassert db.execute('select status from orders').fetchone()[0]=='fulfilled'\nprint('verified')`;const out=spawnSync('python',['-c',program],{input:JSON.stringify({schema:readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'),statements}),encoding:'utf8'});assert.equal(out.status,0,out.stderr);assert.match(out.stdout,/verified/)});
test('invalid webhook cannot write to database',async()=>{let written=false;const r=await api(new Request(origin+'/api/stripe/webhook',{method:'POST',body:'{}',headers:{'Stripe-Signature':'t=1,v1=bad'}}),{STRIPE_WEBHOOK_SECRET:'whsec_test',DB:{batch:()=>{written=true}}});assert.equal(r.status,400);assert.equal(written,false)});

test('Signature checkout rejects a Stripe price that differs from the approved $49',async()=>{const original=globalThis.fetch;let created=false;const DB={prepare:()=>({bind(){return this},run:async()=>({}),first:async()=>({count:1})})};try{globalThis.fetch=async(url)=>{if(url.includes('/prices/'))return Response.json({active:true,type:'one_time',unit_amount:1,currency:'usd'});created=true;return Response.json({})};const r=await api(request('/api/checkout',{requestId:'12345678-1234-1234-1234-123456789abc',items:[{id:'jup-signature',quantity:1}]}),{DB,SESSION_SECRET:secret,SITE_URL:origin,STORE_READY:'true',POLICIES_APPROVED:'true',STRIPE_SECRET_KEY:'sk_test',STRIPE_WEBHOOK_SECRET:'whsec_test',STRIPE_SHIPPING_RATE:'shr_test',STRIPE_PRICE_SIGNATURE:'price_signature'});assert.equal(r.status,409);assert.equal(created,false)}finally{globalThis.fetch=original}});
test('an async success event still requires paid payment status',async()=>{let stored;const DB={prepare:sql=>({bind(...args){return{sql,args}}}),batch:async list=>{stored=list}};const raw=JSON.stringify({id:'evt_async',type:'checkout.session.async_payment_succeeded',data:{object:{id:'cs_test_order',payment_status:'unpaid',metadata:{studio:'jup-life',cart:'[{"id":"jup-signature","quantity":1}]'}}}});const r=await api(new Request(origin+'/api/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':signature(raw)},body:raw}),{DB,STRIPE_WEBHOOK_SECRET:'whsec_test'});assert.equal(r.status,200);assert.equal(stored[0].args[3],'pending')});

test('sandbox refuses live keys before contacting Stripe or D1',async()=>{const env={STRIPE_SANDBOX_ONLY:'true',STRIPE_SECRET_KEY:'rk_live_fake',STORE_READY:'true',POLICIES_APPROVED:'true',DB:{},SESSION_SECRET:secret,SITE_URL:origin,STRIPE_WEBHOOK_SECRET:'whsec_test',STRIPE_SHIPPING_RATE:'shr_test'};const r=await api(request('/api/checkout',{}),env);assert.equal(r.status,503)});
