const encoder=new TextEncoder();
export const PRODUCTS=[
 {id:'hibiscus',name:'The Hibiscus Set',subtitle:'Six blooms + one case',description:'Six TPU 95A hibiscus coasters and one matching case. $29 for the set.',image:'/assets/hibiscus-tpu95-clear-v2.webp',amount:2900,currency:'USD',priceEnv:'STRIPE_PRICE_HIBISCUS'},
 {id:'coaster-set',name:'The JUP LIFE Coasters',subtitle:'Six coastal moments',description:'Six round coasters with the spirit of two chairs and one wave.',image:'/assets/coasters.webp',priceEnv:'STRIPE_PRICE_COASTERS'},
 {id:'coaster-holder',name:'The Open-Air Holder',subtitle:'Everything in its place',description:'An open-sided home for six JUP LIFE coasters, with easy access to the whole stack.',image:'/assets/coasters.webp',priceEnv:'STRIPE_PRICE_HOLDER'},
 {id:'studio-set',name:'The Happy Place Set',subtitle:'The whole little escape',description:'Six JUP LIFE coasters, paired with their open-air holder.',image:'/assets/detail.webp',priceEnv:'STRIPE_PRICE_STUDIO_SET'}
];
const MIME={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm'};
export function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
function fail(message,status=400){const e=new Error(message);e.status=status;throw e}
function requireDb(env){if(!env.DB)fail('The studio is being connected. Please try again later.',503)}
export function requireOrigin(request){const origin=request.headers.get('Origin');if(origin!==new URL(request.url).origin)fail('Request origin not allowed.',403)}
async function data(request){if(Number(request.headers.get('Content-Length')||0)>16384)fail('Request too large.',413);let length=0;const chunks=[];if(request.body){const reader=request.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>16384){void reader.cancel();fail('Request too large.',413)}chunks.push(value)}}const joined=new Uint8Array(length);let offset=0;for(const chunk of chunks){joined.set(chunk,offset);offset+=chunk.length}const text=new TextDecoder().decode(joined);try{return JSON.parse(text)}catch{fail('Invalid JSON.')}}
function plain(value,max=300){if(typeof value!=='string'||value.length>max)fail('Invalid text field.');return value.trim()}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function unb64(s){const str=atob(s.replaceAll('-','+').replaceAll('_','/'));return Uint8Array.from(str,c=>c.charCodeAt(0))}
async function hmac(secret,message){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(message)))}
export async function signSession(secret,now=Date.now()){const payload=b64(encoder.encode(JSON.stringify({exp:Math.floor(now/1000)+28800,nonce:crypto.randomUUID()})));return payload+'.'+b64(await hmac(secret,payload))}
export async function verifySession(token,secret,now=Date.now()){
 if(!secret||secret.length<32||!token||token.length>1024)return false;
 try{const [payload,signature,...rest]=token.split('.');if(rest.length||!payload||!signature)return false;const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',key,unb64(signature),encoder.encode(payload)))return false;const p=JSON.parse(new TextDecoder().decode(unb64(payload)));const t=Math.floor(now/1000);return Number.isInteger(p.exp)&&p.exp>t&&p.exp<=t+28800;}catch{return false}
}
function tokenFrom(request){return (request.headers.get('Cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('jup_session='))?.slice(12)}
async function authenticated(request,env){return verifySession(tokenFrom(request),env.SESSION_SECRET)}
async function requireAdmin(request,env){if(!await authenticated(request,env))fail('Sign in to the studio.',401)}
async function equalSecret(a,b){const hash=async x=>new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(x)));const [ha,hb]=await Promise.all([hash(a),hash(b)]);let d=0;for(let i=0;i<ha.length;i++)d|=ha[i]^hb[i];return d===0}
async function limit(request,env,kind,max,period=600){
 requireDb(env);const ip=request.headers.get('CF-Connecting-IP')||'local';const now=Math.floor(Date.now()/1000);const bucket=Math.floor(now/period);const digest=b64(await hmac(env.SESSION_SECRET||'rate-limit',kind+':'+ip+':'+bucket));
 await env.DB.prepare('INSERT INTO rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').bind(digest,now+period).run();
 const row=await env.DB.prepare('SELECT count FROM rate_limits WHERE key=?').bind(digest).first();if(row.count>max)fail('Please wait a few minutes before trying again.',429);
 if(Math.random()<.05)await env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(now).run();
}
function readiness(env){return env.STORE_READY==='true'&&env.POLICIES_APPROVED==='true'&&!!env.STRIPE_SECRET_KEY&&!!env.STRIPE_WEBHOOK_SECRET&&!!env.STRIPE_SHIPPING_RATE&&!!env.DB&&!!env.SITE_URL&&env.SESSION_SECRET?.length>=32}
export function validateCart(items){if(!Array.isArray(items)||!items.length||items.length>PRODUCTS.length)fail('Choose a product first.');const seen=new Set();return items.map(item=>{if(!item||!PRODUCTS.some(p=>p.id===item.id)||seen.has(item.id)||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>10)fail('Invalid cart.');seen.add(item.id);return {id:item.id,quantity:item.quantity}})}
async function stripe(env,path,method='GET',body,idempotency){const headers={Authorization:'Bearer '+env.STRIPE_SECRET_KEY};if(body)headers['Content-Type']='application/x-www-form-urlencoded';if(idempotency)headers['Idempotency-Key']=idempotency;const r=await fetch('https://api.stripe.com/v1/'+path,{method,headers,body});let out;try{out=await r.json()}catch{fail('Checkout is temporarily unavailable.',502)}if(!r.ok)fail('Checkout is temporarily unavailable. Please contact Dee.',502);return out}
async function price(env,id){const p=await stripe(env,'prices/'+encodeURIComponent(id));if(!p.active||p.type!=='one_time'||!Number.isInteger(p.unit_amount)||p.unit_amount<1||typeof p.currency!=='string')fail('This product is not ready for checkout.',409);return p}
async function catalog(env){const ready=readiness(env);const products=await Promise.all(PRODUCTS.map(async p=>{let amount=p.amount??null,currency=p.currency??null,available=false;if(ready&&/^price_[a-zA-Z0-9]+$/.test(env[p.priceEnv]||'')){try{const v=await price(env,env[p.priceEnv]);if(p.id==='hibiscus'&&(v.unit_amount!==2900||v.currency!=='usd'))throw Error('Hibiscus price must be $29 USD');amount=v.unit_amount;currency=v.currency;available=true}catch{}}const {priceEnv,...publicProduct}=p;return {...publicProduct,amount,currency,available}}));return {products,checkoutReady:ready&&products.some(p=>p.available)}}
async function checkout(request,env){requireOrigin(request);if(!readiness(env))fail('The collection is coming soon. Contact Dee for details.',503);await limit(request,env,'checkout',20);const body=await data(request);const items=validateCart(body.items);if(typeof body.requestId!=='string'||!/^[a-f0-9-]{36}$/i.test(body.requestId))fail('Invalid checkout request.');const cart=items.sort((a,b)=>a.id.localeCompare(b.id));const currencies=new Set();const form=new URLSearchParams({mode:'payment',success_url:env.SITE_URL.replace(/\/$/,'')+'/success?session_id={CHECKOUT_SESSION_ID}',cancel_url:env.SITE_URL.replace(/\/$/,'')+'/?checkout=cancelled#collection','shipping_options[0][shipping_rate]':env.STRIPE_SHIPPING_RATE,'consent_collection[terms_of_service]':'required','metadata[studio]':'jup-life','metadata[cart]':JSON.stringify(cart)});
 for(let i=0;i<cart.length;i++){const p=PRODUCTS.find(p=>p.id===cart[i].id);const id=env[p.priceEnv];if(!/^price_[a-zA-Z0-9]+$/.test(id||''))fail('This product is not ready for checkout.',409);const v=await price(env,id);if(p.id==='hibiscus'&&(v.unit_amount!==2900||v.currency!=='usd'))fail('Hibiscus checkout price needs attention.',409);currencies.add(v.currency);form.set(`line_items[${i}][price]`,id);form.set(`line_items[${i}][quantity]`,String(cart[i].quantity));}
 if(currencies.size!==1)fail('These products cannot be checked out together.',409);
 const countries=(env.SHIPPING_COUNTRIES||'US').split(',').map(c=>c.trim().toUpperCase());if(!countries.length||countries.length>20||countries.some(c=>!/^[A-Z]{2}$/.test(c)))fail('Shipping setup needs attention.',503);countries.forEach((c,i)=>form.set(`shipping_address_collection[allowed_countries][${i}]`,c));if(env.STRIPE_AUTOMATIC_TAX==='true')form.set('automatic_tax[enabled]','true');
 const idem='jup-'+body.requestId+'-'+b64(await hmac(env.SESSION_SECRET,JSON.stringify(cart)));const session=await stripe(env,'checkout/sessions','POST',form.toString(),idem);if(typeof session.url!=='string'||(new URL(session.url).hostname!=='checkout.stripe.com'||new URL(session.url).protocol!=='https:'))fail('Checkout could not be started.',502);
 await env.DB.prepare('INSERT INTO orders(id,stripe_session_id,items_json,status) VALUES(?,?,?,?) ON CONFLICT(stripe_session_id) DO NOTHING').bind(crypto.randomUUID(),session.id,JSON.stringify(cart),'pending').run();return json({url:session.url});}
export async function verifyStripeSignature(raw,header,secret,now=Date.now()){
 if(!header||!secret)return false;const fields=header.split(',').map(s=>s.trim().split('='));const t=Number(fields.find(f=>f[0]==='t')?.[1]);const signatures=fields.filter(f=>f[0]==='v1').map(f=>f[1]);if(!Number.isSafeInteger(t)||Math.abs(now/1000-t)>300)return false;
 const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);for(const s of signatures){if(!/^[a-f0-9]{64}$/i.test(s||''))continue;const bytes=Uint8Array.from(s.match(/../g),x=>parseInt(x,16));if(await crypto.subtle.verify('HMAC',key,bytes,encoder.encode(t+'.'+raw)))return true;}return false;
}
async function webhook(request,env){if(!env.STRIPE_WEBHOOK_SECRET)fail('Webhook is not configured.',503);requireDb(env);if(Number(request.headers.get('Content-Length')||0)>1048576)fail('Event too large.',413);const raw=await request.text();if(raw.length>1048576)fail('Event too large.',413);if(!await verifyStripeSignature(raw,request.headers.get('Stripe-Signature'),env.STRIPE_WEBHOOK_SECRET))fail('Invalid event signature.',400);let event;try{event=JSON.parse(raw)}catch{fail('Invalid event.',400)}if(!/^evt_[a-zA-Z0-9]+$/.test(event.id||''))fail('Invalid event.');
 const relevant=['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'];if(!relevant.includes(event.type))return json({received:true});const s=event.data?.object;if(s?.metadata?.studio!=='jup-life')return json({received:true});
 const paid=event.type==='checkout.session.async_payment_succeeded'||(event.type==='checkout.session.completed'&&s.payment_status==='paid');const status=paid?'paid':event.type==='checkout.session.async_payment_failed'?'failed':event.type==='checkout.session.expired'?'expired':'pending';
 // One D1 transactional batch: dedupe and persist payment state together; retries cannot double-fulfill.
 // Orders can arrive via webhook before checkout's local insert; metadata recovers the server-validated cart.
 const items=validateCart(JSON.parse(s.metadata.cart||'[]'));const amount=s.amount_total??null;const currency=s.currency??null;
 await env.DB.batch([
 env.DB.prepare('INSERT INTO orders(id,stripe_session_id,items_json,status,amount_total,currency) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM stripe_events WHERE id=?) ON CONFLICT(stripe_session_id) DO UPDATE SET status=CASE WHEN orders.status IN (\'paid\',\'fulfilled\') THEN orders.status ELSE excluded.status END, amount_total=COALESCE(excluded.amount_total,orders.amount_total), currency=COALESCE(excluded.currency,orders.currency), updated_at=CURRENT_TIMESTAMP').bind(crypto.randomUUID(),s.id,JSON.stringify(items),status,amount,currency,event.id),
 env.DB.prepare('INSERT OR IGNORE INTO stripe_events(id,event_type) VALUES(?,?)').bind(event.id,event.type)]);return json({received:true});}
export function sniffType(bytes,type){if(type==='image/png')return [137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b);if(type==='image/jpeg')return bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(type==='image/webp')return new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';if(type==='video/mp4')return new TextDecoder().decode(bytes.slice(4,8))==='ftyp';if(type==='video/webm')return [26,69,223,163].every((b,i)=>bytes[i]===b);return false}
async function upload(request,env){requireOrigin(request);await requireAdmin(request,env);requireDb(env);if(!env.MEDIA)fail('Media storage is not connected.',503);const type=request.headers.get('Content-Type')?.split(';')[0];if(!MIME[type])fail('Use JPG, PNG, WebP, MP4 or WebM.');const size=Number(request.headers.get('Content-Length'));const max=type.startsWith('image/')?20*1024*1024:75*1024*1024;if(!Number.isInteger(size)||size<16||size>max)fail('Images may be up to 20 MB; videos up to 75 MB.',413);
 const clone=request.clone();const reader=clone.body.getReader();const {value}=await reader.read();void reader.cancel().catch(()=>{});if(!value||!sniffType(value,type))fail('The file contents do not match the selected format.');let originalName;try{originalName=decodeURIComponent(request.headers.get('X-File-Name')||'upload')}catch{fail('Invalid filename.')}originalName=plain(originalName,180);const id=crypto.randomUUID();const key=id+'.'+MIME[type];
 await env.MEDIA.put(key,request.body,{httpMetadata:{contentType:type},customMetadata:{studio:'jup-life'}});
 try{await env.DB.prepare('INSERT INTO media(id,object_key,content_type,bytes,original_name) VALUES(?,?,?,?,?)').bind(id,key,type,size,originalName).run()}catch(e){await env.MEDIA.delete(key);throw e}return json({id,url:'/media/'+id,published:false},201);}
async function adminRoutes(request,env,path){
 if(path==='/api/admin/login'&&request.method==='POST'){requireOrigin(request);if(!env.ADMIN_PASSWORD||env.ADMIN_PASSWORD.length<16||!env.SESSION_SECRET||env.SESSION_SECRET.length<32)fail('Studio sign-in is not configured yet.',503);await limit(request,env,'login',8);const body=await data(request);const password=plain(body.password,256);if(!await equalSecret(password,env.ADMIN_PASSWORD))fail('Unable to sign in.',401);const token=await signSession(env.SESSION_SECRET);return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':`jup_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`}});}
 if(path==='/api/admin/logout'&&request.method==='POST'){requireOrigin(request);return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':'jup_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'}})}
 await requireAdmin(request,env);requireDb(env);
 if(path==='/api/admin/session'&&request.method==='GET')return json({signedIn:true});
 if(path==='/api/admin/status'&&request.method==='GET')return json({mediaConnected:!!env.MEDIA,databaseConnected:!!env.DB,checkoutReady:readiness(env),pricesConfigured:PRODUCTS.map(p=>({name:p.name,configured:!!env[p.priceEnv]}))});
 if(path==='/api/admin/media'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM media ORDER BY created_at DESC LIMIT 200').all();return json({items:r.results.map(m=>({...m,url:'/media/'+m.id}))});}
 if(path==='/api/admin/media'&&request.method==='POST')return upload(request,env);
 if(path==='/api/admin/quotes'&&request.method==='POST'){requireOrigin(request);const b=await data(request);const text=plain(b.text,800);if(!text)fail('Write a quote first.');const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO media(id,object_key,content_type,bytes,original_name,title,category) VALUES(?,?,?,?,?,?,?)').bind(id,'quote/'+id,'text/plain',new TextEncoder().encode(text).length,'Mrs. Smash quote',text,'quote').run();return json({id,published:false},201);}

 const mediaMatch=path.match(/^\/api\/admin\/media\/([a-f0-9-]{36})$/);if(mediaMatch){requireOrigin(request);const id=mediaMatch[1];const m=await env.DB.prepare('SELECT * FROM media WHERE id=?').bind(id).first();if(!m)fail('Media not found.',404);
 if(request.method==='PATCH'){const b=await data(request);const title=plain(b.title,m.content_type==='text/plain'?800:160),alt=plain(b.alt,300),category=plain(b.category,30);const productId=b.productId||null;if(category==='product'&&!PRODUCTS.some(p=>p.id===productId))fail('Choose a collection piece.');if(!['journal','product','hero','quote'].includes(category)||typeof b.published!=='boolean')fail('Invalid media settings.');if((m.content_type==='text/plain')!==(category==='quote'))fail('Quotes stay in Point of View; use photo or video uploads for other sections.');if(category==='hero'&&!m.content_type.startsWith('image/'))fail('Use a photo for the homepage; videos can be studio notes or collection media.');if(b.published&&(!title||(category!=='quote'&&!m.content_type.startsWith('video/')&&!alt)))fail('Add a title and image description before publishing.');await env.DB.prepare('UPDATE media SET title=?,alt=?,category=?,product_id=?,published=? WHERE id=?').bind(title,alt,category,category==='product'?productId:null,b.published?1:0,id).run();return json({ok:true});}
 if(request.method==='DELETE'){if(m.content_type!=='text/plain'){if(!env.MEDIA)fail('Media storage is not connected.',503);await env.MEDIA.delete(m.object_key);}await env.DB.prepare('DELETE FROM media WHERE id=?').bind(id).run();return json({ok:true});}}
 if(path==='/api/admin/orders'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 100').all();return json({orders:r.results});}
 const orderMatch=path.match(/^\/api\/admin\/orders\/([a-f0-9-]{36})$/);if(orderMatch&&request.method==='PATCH'){requireOrigin(request);const b=await data(request);if(b.status!=='fulfilled')fail('Invalid order state.');const r=await env.DB.prepare('UPDATE orders SET status=\'fulfilled\',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=\'paid\'').bind(orderMatch[1]).run();if(r.meta?.changes!==1)fail('Only a paid order can be marked fulfilled.',409);return json({ok:true});}
 fail('Not found.',404);
}
export async function handleApi(context){const {request,env}=context;const path=new URL(request.url).pathname;try{
 if(path==='/api/catalog'&&request.method==='GET')return json(await catalog(env));
 if(path==='/api/media'&&request.method==='GET'){if(!env.DB)return json({items:[]});const r=await env.DB.prepare('SELECT id,title,alt,category,product_id,content_type,created_at FROM media WHERE published=1 ORDER BY created_at DESC LIMIT 40').all();return json({items:r.results.map(m=>({...m,url:'/media/'+m.id}))});}
 if(path==='/api/checkout'&&request.method==='POST')return await checkout(request,env);
 if(path==='/api/stripe/webhook'&&request.method==='POST')return await webhook(request,env);
 if(path==='/api/checkout/status'&&request.method==='GET'){const id=new URL(request.url).searchParams.get('session_id');if(!/^cs_(test_|live_)?[a-zA-Z0-9]+$/.test(id||''))fail('Invalid order reference.');requireDb(env);const row=await env.DB.prepare('SELECT status FROM orders WHERE stripe_session_id=?').bind(id).first();return json({status:row?.status||'pending'});}
 if(path.startsWith('/api/admin/'))return await adminRoutes(request,env,path);
 return json({error:'Not found.'},404);
 }catch(e){if(!e.status)console.error('JUP API error',e.name);return json({error:e.status?e.message:'The studio is temporarily unavailable. Please try again.'},e.status||500);}}
export async function handleMedia({request,env}){try{if(!['GET','HEAD'].includes(request.method))fail('Method not allowed.',405);requireDb(env);if(!env.MEDIA)fail('Media unavailable.',503);const id=new URL(request.url).pathname.split('/').pop();if(!/^[a-f0-9-]{36}$/.test(id||''))fail('Not found.',404);const item=await env.DB.prepare('SELECT * FROM media WHERE id=?').bind(id).first();if(!item||(!item.published&&!await authenticated(request,env)))fail('Not found.',404);const meta=await env.MEDIA.head(item.object_key);if(!meta)fail('Not found.',404);const headers=new Headers({'Content-Type':item.content_type,'X-Content-Type-Options':'nosniff','Cache-Control':item.published?'public, max-age=3600':'private, no-store','Accept-Ranges':'bytes','ETag':meta.httpEtag});let range,status=200;const raw=request.headers.get('Range');if(raw){const match=raw.match(/^bytes=(\d*)-(\d*)$/);if(!match||(!match[1]&&!match[2]))return new Response(null,{status:416,headers:{'Content-Range':`bytes */${meta.size}`}});let start=match[1]?Number(match[1]):Math.max(0,meta.size-Number(match[2]));let end=match[1]?(match[2]?Number(match[2]):meta.size-1):meta.size-1;if(start>=meta.size||end<start||!Number.isSafeInteger(start)||!Number.isSafeInteger(end))return new Response(null,{status:416,headers:{'Content-Range':`bytes */${meta.size}`}});end=Math.min(end,meta.size-1);range={offset:start,length:end-start+1};status=206;headers.set('Content-Range',`bytes ${start}-${end}/${meta.size}`);headers.set('Content-Length',String(end-start+1));}else headers.set('Content-Length',String(meta.size));if(request.method==='HEAD')return new Response(null,{status,headers});const obj=await env.MEDIA.get(item.object_key,range?{range}:undefined);return new Response(obj.body,{status,headers});}catch(e){return json({error:e.status?e.message:'Media unavailable.'},e.status||500)}}



